# Generated by Django 6.0.4 on 2026-04-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_contactmessage_newslettersubscriber_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feature_requested',
            field=models.BooleanField(default=False, help_text='Author has asked an editor to consider featuring this post.'),
        ),
    ]
